# Generated by Django 3.1.7 on 2025-02-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20221214_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='product_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='product',
            field=models.CharField(default='p', max_length=64),
            preserve_default=False,
        ),
    ]
